version: "2"
services:
    strongswan:
        build: .
        image: ajslater/strongswan
        container_name: strongswan
        ports:
            - "500:500/udp" # IKE
            - "4500:4500/udp" # IKE for NAT & MOBIKE
        privileged: true
        cap_add:
            - NET_ADMIN
        entrypoint: /run.sh
