version: 2.1
jobs:
  strongswan-build:
    machine: true
    steps:
      - checkout
      - run: ./build.sh
workflows:
  build:
    jobs:
      - strongswan-build:
        pre-steps:
          - run: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        post-steps:
          - run: ./tag-and-push.sh
