version: 2.1
executors:
    docker-publisher:
        machine: true

parameters:
  image_archive:
    type: string
    default: "image.tar"

jobs:
  build:
    executor: docker-publisher
    steps:
    - checkout
    - run:
        name: Build Strongswan
        command: ./build.sh
    - run:
        name: Archive Docker image
        command: ./ci/archive-image.sh ./<< pipeline.parameters.image_archive >>
    - persist_to_workspace:
        root: .
        paths:
        - ./<< pipeline.parameters.image_archive >>
        - ./env
        - ./ci/tag-and-push.sh
  deploy:
    executor: docker-publisher
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Load archive Docker image
        command: docker load -i "./<< pipeline.parameters.image_archive >>"
    - run:
        name: Publish Docker Image to Docker Hub
        command: ./ci/tag-and-push.sh

workflows:
  version: 2.1
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
